@echo off
@REM start cmd /c "python main.py --logic Random --email=test@email.com --name=stima --password=123456 --team etimo"
@REM start cmd /c "python main.py --logic Random --email=test1@email.com --name=stima1 --password=123456 --team etimo"
@REM start cmd /c "python main.py --logic Random --email=test2@email.com --name=stima2 --password=123456 --team etimo"
@REM start cmd /c "python main.py --logic Asisten --email=test4@email.com --name=stima3 --password=1256 --team etimo"
    
@REM start cmd /c "python main.py --logic ArticaKenapaBatal --email=ArticaKenapaBatal@email.com --name=arctica --password=123456 --team etimo"
@REM start cmd /c "python main.py --logic Cijawjaw --email=Cijawjaw@email.com --name=cijawjaw --password=123456 --team etimo"
@REM start cmd /c "python main.py --logic DNA --email=DNA@email.com --name=dna --password=123456 --team etimo"
@REM start cmd /c "python main.py --logic Dujari --email=Dujari@email.com --name=dujari --password=123456 --team etimo"
@REM start cmd /c "python main.py --logic QUEEN --email=QUEEN@email.com --name=queen --password=123456 --team etimo"
@REM start cmd /c "python main.py --logic terkesTima --email=terkesTima@email.com --name=terkestima --password=123456 --team etimo"
@REM start cmd /c "python main.py --logic TheYuds --email=TheYuds@email.com --name=theyuds --password=123456 --team etimo"

@REM start cmd /c "python main.py --logic OlahragaGuntur --email=OlahragaGuntur@email.com --name=olhragagtr --password=123456 --team etimo"
@REM start cmd /c "python main.py --logic SambutRamadhan --email=SambutRamadhan@email.com --name=ramadhan --password=123456 --team etimo"
@REM start cmd /c "python main.py --logic MrNaginski --email=MrNaginski@email.com --name=mrnaginski --password=123456 --team etimo"
@REM start cmd /c "python main.py --logic TipisTipis --email=TipisTipis@email.com --name=tipistipis --password=123456 --team etimo"
@REM start cmd /c "python main.py --logic Tulas --email=Tulas@email.com --name=tulas --password=123456 --team etimo"
@REM start cmd /c "python main.py --logic TonggokuNyalegNdes --email=TonggokuNyalegNdes@email.com --name=nyalegndes --password=123456 --team etimo"
@REM start cmd /c "python main.py --logic Janggar --email=janggar@email.com --name=janggar --password=123456 --team etimo"

@REM start cmd /c "python main.py --logic UrbanGym --email=UrbanGym@email.com --name=urbangym --password=123456 --team etimo"
@REM start cmd /c "python main.py --logic Bingung --email=Bingung@email.com --name=bingung --password=123456 --team etimo"
@REM start cmd /c "python main.py --logic Silverqueen --email=Silverqueen@email.com --name=silvrqueen --password=123456 --team etimo"
@REM start cmd /c "python main.py --logic HolderRNDR --email=HolderRNDR@email.com --name=holderrndr --password=123456 --team etimo"
@REM start cmd /c "python main.py --logic TuanKrabs --email=TuanKrabs@email.com --name=tuankrabs --password=123456 --team etimo"
@REM start cmd /c "python main.py --logic Metiuganteng --email=Metiuganteng@email.com --name=metiugntng --password=123456 --team etimo"
@REM start cmd /c "python main.py --logic Robotnik --email=Robotnik@email.com --name=robotnik --password=123456 --team etimo"
@REM start cmd /c "python main.py --logic Kelompok56 --email=Kelompok56@email.com --name=kelompok56 --password=123456 --team etimo"

@REM start cmd /c "python main.py --logic tbfoReborn --email=tbfoReborn@email.com --name=tbforeborn --password=123456 --team etimo"
@REM start cmd /c "python main.py --logic susugratis --email=susugratis@email.com --name=susugratis --password=123456 --team etimo"
@REM start cmd /c "python main.py --logic gatauHehe --email=gatauHehe@email.com --name=gatauhehe --password=123456 --team etimo"
@REM start cmd /c "python main.py --logic SiniMainSamaOm --email=SiniMainSamaOm@email.com --name=sinimain --password=123456 --team etimo"
@REM start cmd /c "python main.py --logic ilmuPadi --email=ilmuPadi@email.com --name=ilmupadi --password=123456 --team etimo"
@REM start cmd /c "python main.py --logic MVP --email=MVP@email.com --name=mvp --password=123456 --team etimo"
@REM start cmd /c "python main.py --logic SulfatGemoy --email=SulfatGemoy@email.com --name=sulfatgmoy --password=123456 --team etimo"

@REM start cmd /c "python main.py --logic FreeDiamonds --email=FreeDiamonds@email.com --name=freediamon --password=123456 --team etimo"
@REM start cmd /c "python main.py --logic NamaKelompoknyaNanti --email=NamaKelompoknyaNanti@email.com --name=nanti --password=123456 --team etimo"
@REM start cmd /c "python main.py --logic NanangBoneng --email=NanangBoneng@email.com --name=nanangbng --password=123456 --team etimo"
@REM start cmd /c "python main.py --logic omega --email=omega@email.com --name=omega --password=123456 --team etimo"
@REM start cmd /c "python main.py --logic savage --email=savage@email.com --name=savage --password=123456 --team etimo"
@REM start cmd /c "python main.py --logic SutaLovesEmyu --email=SutaLovesEmyu@email.com --name=sutaemyu --password=123456 --team etimo"
@REM start cmd /c "python main.py --logic TBD --email=TBD@email.com --name=tbd --password=123456 --team etimo"

@REM start cmd /c "python main.py --logic ALLINRM --email=ALLINRM@email.com --name=allinrm --password=123456 --team etimo"
@REM start cmd /c "python main.py --logic Alucard --email=Alucard@email.com --name=alucard --password=123456 --team etimo"
@REM start cmd /c "python main.py --logic JadiMesin --email=JadiMesin@email.com --name=jadimesin --password=123456 --team etimo"
@REM start cmd /c "python main.py --logic PCS --email=PCS@email.com --name=pcs --password=123456 --team etimo"
@REM start cmd /c "python main.py --logic ReelaIndo --email=ReelaIndo@email.com --name=reelaindo --password=123456 --team etimo"
@REM start cmd /c "python main.py --logic SanssKuy --email=SanssKuy@email.com --name=sansskuy --password=123456 --team etimo"
@REM start cmd /c "python main.py --logic SurtiTejo --email=SurtiTejo@email.com --name=surtitejo --password=123456 --team etimo"
@REM start cmd /c "python main.py --logic WLM --email=WLM@email.com --name=wlm --password=123456 --team etimo"

@REM start cmd /c "python main.py --logic DevilTears --email=DevilTears@email.com --name=deviltears --password=123456 --team etimo"
@REM start cmd /c "python main.py --logic Akiong --email=Akiong@email.com --name=akiong --password=123456 --team etimo"
@REM start cmd /c "python main.py --logic Bawastub --email=Bawastub@email.com --name=bawastub --password=123456 --team etimo"
@REM start cmd /c "python main.py --logic Drive2011 --email=Drive2011@email.com --name=drive2011 --password=123456 --team etimo"
@REM start cmd /c "python main.py --logic Istiqamah --email=Istiqamah@email.com --name=istiqamah --password=123456 --team etimo"
@REM start cmd /c "python main.py --logic PinjamDulu100v2 --email=Pinjam100@email.com --name=pinjam100 --password=123456 --team etimo"
@REM start cmd /c "python main.py --logic Snoopy --email=Snoopy@email.com --name=snoopy --password=123456 --team etimo"

@REM start cmd /c "python main.py --logic FirstToTheKeyFirstToTheEggBot --email=firsttoegg@email.com --name=firsttoegg --password=123456 --team etimo"
@REM start cmd /c "python main.py --logic WadasJanggar --email=wadasjanggar@email.com --name=wdsjanggar --password=123456 --team etimo"
@REM start cmd /c "python main.py --logic blinkBlink --email=blinkblink@email.com --name=blinkblink --password=123456 --team etimo"
@REM start cmd /c "python main.py --logic SarikatJava --email=sarikatjava@email.com --name=srikatjava --password=123456 --team etimo"
@REM start cmd /c "python main.py --logic Oogoe_Diamonds --email=oogoediamonds@email.com --name=oogoe --password=123456 --team etimo"
@REM start cmd /c "python main.py --logic KoinOndo --email=koinondo@email.com --name=koinondo --password=123456 --team etimo"
@REM start cmd /c "python main.py --logic OkeGas --email=okegas@email.com --name=okegas --password=123456 --team etimo"
