@echo off
start cmd /c "python main.py --logic Random --email=test@email.com --name=stima --password=123456 --team etimo"
start cmd /c "python main.py --logic Random --email=test1@email.com --name=stima1 --password=123456 --team etimo"
start cmd /c "python main.py --logic Random --email=test2@email.com --name=stima2 --password=123456 --team etimo"
start cmd /c "python main.py --logic Asisten --email=test4@email.com --name=Asisten --password=1256 --team etimo"

    
start cmd /c "python main.py --logic ArticaKenapaBatal --email=ArticaKenapaBatal@email.com --name=ArticaKenapaBatal --password=123456 --team etimo"
start cmd /c "python main.py --logic Cijawjaw --email=Cijawjaw@email.com --name=Cijawjaw --password=123456 --team etimo"
start cmd /c "python main.py --logic DNA --email=DNA@email.com --name=DNA --password=123456 --team etimo"
start cmd /c "python main.py --logic Dujari --email=Dujari@email.com --name=Dujari --password=123456 --team etimo"
start cmd /c "python main.py --logic QUEEN --email=QUEEN@email.com --name=QUEEN --password=123456 --team etimo"
start cmd /c "python main.py --logic terkesTima --email=terkesTima@email.com --name=terkesTima --password=123456 --team etimo"
start cmd /c "python main.py --logic TheYuds --email=TheYuds@email.com --name=TheYuds --password=123456 --team etimo"

start cmd /c "python main.py --logic OlahragaGuntur --email=OlahragaGuntur@email.com --name=OlahragaGuntur --password=123456 --team etimo"
start cmd /c "python main.py --logic SambutRamadhan --email=SambutRamadhan@email.com --name=SambutRamadhan --password=123456 --team etimo"
start cmd /c "python main.py --logic MrNaginski --email=MrNaginski@email.com --name=MrNaginski --password=123456 --team etimo"
start cmd /c "python main.py --logic TipisTipis --email=TipisTipis@email.com --name=TipisTipis --password=123456 --team etimo"
start cmd /c "python main.py --logic Tulas --email=Tulas@email.com --name=Tulas --password=123456 --team etimo"
start cmd /c "python main.py --logic TonggokuNyalegNdes --email=TonggokuNyalegNdes@email.com --name=TonggokuNyalegNdes --password=123456 --team etimo"
start cmd /c "python main.py --logic Janggar --email=Janggar@email.com --name=Janggar --password=123456 --team etimo"

start cmd /c "python main.py --logic UrbanGym--email=UrbanGym@email.com --name=UrbanGym --password=123456 --team etimo"
start cmd /c "python main.py --logic Bingung --email=Bingung@email.com --name=Bingung --password=123456 --team etimo"
start cmd /c "python main.py --logic Silverqueen --email=Silverqueen@email.com --name=Silverqueen --password=123456 --team etimo"
start cmd /c "python main.py --logic HolderRNDR --email=HolderRNDR@email.com --name=HolderRNDR --password=123456 --team etimo"
start cmd /c "python main.py --logic TuanKrabs --email=TuanKrabs@email.com --name=TuanKrabs --password=123456 --team etimo"
start cmd /c "python main.py --logic Metiuganteng --email=Metiuganteng@email.com --name=Metiuganteng --password=123456 --team etimo"
start cmd /c "python main.py --logic Robotnik --email=Robotnik@email.com --name=Robotnik --password=123456 --team etimo"
start cmd /c "python main.py --logic Kelompok56 --email=Kelompok56@email.com --name=Kelompok56 --password=123456 --team etimo"

start cmd /c "python main.py --logic tbfoReborn --email=tbfoReborn@email.com --name=tbfoReborn --password=123456 --team etimo"
start cmd /c "python main.py --logic susugratis --email=susugratis@email.com --name=susugratis --password=123456 --team etimo"
start cmd /c "python main.py --logic gatauHehe --email=gatauHehe@email.com --name=gatauHehe --password=123456 --team etimo"
start cmd /c "python main.py --logic SiniMainSamaOm --email=SiniMainSamaOm@email.com --name=SiniMainSamaOm --password=123456 --team etimo"
start cmd /c "python main.py --logic ilmuPadi --email=ilmuPadi@email.com --name=ilmuPadi --password=123456 --team etimo"
start cmd /c "python main.py --logic MVP --email=MVP@email.com --name=MVP --password=123456 --team etimo"
start cmd /c "python main.py --logic SulfatGemoy --email=SulfatGemoy@email.com --name=SulfatGemoy --password=123456 --team etimo"

start cmd /c "python main.py --logic FreeDiamonds --email=FreeDiamonds@email.com --name=FreeDiamonds --password=123456 --team etimo"
start cmd /c "python main.py --logic NamaKelompoknyaNanti --email=NamaKelompoknyaNanti@email.com --name=NamaKelompoknyaNanti --password=123456 --team etimo"
start cmd /c "python main.py --logic NanangBoneng --email=NanangBoneng@email.com --name=NanangBoneng --password=123456 --team etimo"
start cmd /c "python main.py --logic omega --email=omega@email.com --name=omega --password=123456 --team etimo"
start cmd /c "python main.py --logic savage --email=savage@email.com --name=savage --password=123456 --team etimo"
start cmd /c "python main.py --logic SutaLovesEmyu --email=SutaLovesEmyu@email.com --name=SutaLovesEmyu --password=123456 --team etimo"
start cmd /c "python main.py --logic TBD --email=TBD@email.com --name=TBD --password=123456 --team etimo"
